/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check endpoint. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server is healthy. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for a JWT access token. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "username": "alice",
                     *       "password": "hunter2"
                     *     }
                     */
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Successful login. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /**
                 * @description Authentication failed. The `message` distinguishes the cause:
                 *     `user not found`, `invalid credentials`, or `user disabled`.
                 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's sessions, newest first. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session list (empty array when none exist). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionListResponse"];
                    };
                };
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        /**
         * Create a new session.
         * @description The server mints a UUID v7 session_id, persists the session row, and
         *     returns it. Clients must create a session before sending messages.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session created successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateSessionResponse"];
                    };
                };
                500: components["responses"]["Internal"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the messages of a session with cursor pagination.
         * @description Returns the full event stream of a session owned by the authenticated
         *     user. Messages are ordered by `(msg_time, msg_index)` ascending by
         *     default; use `order=desc` to retrieve newest first. Pass
         *     `page_token` from the previous response to advance pages.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Opaque cursor from the previous page's `next_page_token`. */
                    page_token?: string;
                    /** @description Number of messages per page. Values above 200 are clamped. */
                    page_size?: number;
                    /** @description Sort order for `(msg_time, msg_index)`. */
                    order?: "asc" | "desc";
                };
                header?: never;
                path: {
                    session_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated message list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionMessagesResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        /**
         * Send a user message and stream the agent's response as SSE.
         * @description The session must already exist and belong to the authenticated user.
         *     Sending to a non-existent session or another user's session returns 404.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    session_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendMessageRequest"];
                };
            };
            responses: {
                /**
                 * @description Server-Sent Events stream. Each event is two lines:
                 *     `event: <type>` and `data: <json>` followed by a blank line.
                 *     Event types: `agent_start`, `token`, `reasoning`, `tool_call`, `agent_end`,
                 *     `agent_error`, `done`. The `done` event is always the final event.
                 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["SSEAgentStart"] | components["schemas"]["SSEToken"] | components["schemas"]["SSEReasoning"] | components["schemas"]["SSEToolCall"] | components["schemas"]["SSEAgentEnd"] | components["schemas"]["SSEAgentError"] | components["schemas"]["SSEDone"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["Internal"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List files in (a subdirectory of) the user's workspace. */
        get: {
            parameters: {
                query?: {
                    /** @description Optional workspace-relative subdirectory. Defaults to the workspace root. */
                    path?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File/dir entries, sorted (directories first, then name). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileListResponse"];
                    };
                };
                403: components["responses"]["Forbidden"];
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a file into the user's workspace. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                        /** @description Destination subdirectory (empty/absent means root). */
                        path?: string;
                    };
                };
            };
            responses: {
                /** @description Upload succeeded. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
                /** @description Uploaded file exceeds the 50 MiB size limit. */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["Internal"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a workspace file as raw bytes.
         * @description The `path` parameter is a workspace-relative path (which may contain
         *     slashes). `path` ending in `/content` selects the text-content
         *     endpoint instead. The content-type of the response reflects the
         *     file's extension.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Workspace-relative file path (catch-all, may include `/`).
                     * @example reports/2026-q2.md
                     */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File bytes; content-type varies by extension. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                /** @description Path resolves to a directory. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace/files/{path}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a workspace file's text content as JSON. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Workspace-relative file path (catch-all, may include `/`). */
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Decoded text content of the file. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileContentResponse"];
                    };
                };
                /** @description File is binary or path is a directory. Use the download endpoint for binary files. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mcp/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the combined MCP tool catalogue.
         * @description Returns the combined tool catalogue: regular Xizhi registry tools,
         *     tools advertised by configured external MCP servers, and the synthetic
         *     `invoke_chongzhi` / `invoke_liang` agent-invocation tools. Each entry
         *     follows the OpenAI function-tool shape (`type: function`).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tool list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MCPToolsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's skills. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Skill list (empty array when none exist). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SkillsResponse"];
                    };
                };
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /**
                 * @description Stable machine-readable error code.
                 * @example BAD_REQUEST
                 */
                code: string;
                /**
                 * @description Human-readable error description.
                 * @example invalid request body
                 */
                message: string;
            };
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        LoginResponse: {
            /** @description Signed JWT to send as `Bearer` in subsequent requests. */
            access_token: string;
            /**
             * Format: int64
             * @description Token expiry as a Unix timestamp (seconds).
             */
            expire: number;
            /**
             * @example Bearer
             * @enum {string}
             */
            token_type: "Bearer";
        };
        SessionListEntry: {
            session_id: string;
            title: string;
            /**
             * Format: date-time
             * @description RFC3339 timestamp of the last update.
             */
            update_time: string;
        };
        SessionListResponse: {
            sessions: components["schemas"]["SessionListEntry"][];
        };
        CreateSessionResponse: {
            /**
             * Format: uuid
             * @description Server-generated UUID v7 session identifier.
             * @example 018f9b8a-7c1a-7e6a-8e6a-6c1a7c1a7c1a
             */
            session_id: string;
        };
        Message: {
            /** Format: int64 */
            id: number;
            /** Format: uuid */
            session_id: string;
            /** Format: date-time */
            msg_time: string;
            /** @enum {string} */
            agent: "user" | "Confuse" | "Chongzhi" | "Liang";
            msg_index: number;
            /** @enum {string} */
            role: "user" | "assistant" | "tool";
            /** @enum {string} */
            event_type: "message" | "token" | "tool_call" | "agent_start" | "agent_end" | "agent_error" | "reasoning";
            content: string;
            /** Format: uuid */
            trace_id: string;
            /** Format: date-time */
            update_time: string;
        };
        SessionMessagesResponse: {
            messages: components["schemas"]["Message"][];
            /** @description Opaque cursor for the next page. Absent on the final page. */
            next_page_token?: string;
        };
        SendMessageRequest: {
            /** @description User message text (must be non-empty). */
            content: string;
        };
        SSEAgentStart: {
            /** @enum {string} */
            type: "agent_start";
            agent: string;
        };
        SSEToken: {
            /** @enum {string} */
            type: "token";
            agent: string;
            /** @description Incremental text token. */
            content: string;
        };
        SSEReasoning: {
            /** @enum {string} */
            type: "reasoning";
            agent: string;
            /** @description Incremental reasoning/thinking token. */
            content: string;
        };
        SSEToolCall: {
            /** @enum {string} */
            type: "tool_call";
            agent: string;
            /** @description Tool name. */
            content: string;
            meta?: {
                args?: {
                    [key: string]: unknown;
                };
            };
        };
        SSEAgentEnd: {
            /** @enum {string} */
            type: "agent_end";
            agent: string;
        };
        SSEAgentError: {
            /** @enum {string} */
            type: "agent_error";
            agent: string;
            /** @description Error message. */
            content: string;
            meta?: {
                error_code?: string;
            };
        };
        SSEDone: {
            /** @enum {string} */
            type: "done";
            meta: {
                usage: {
                    prompt_tokens: number;
                    completion_tokens: number;
                    total_tokens: number;
                };
            };
        };
        FileEntry: {
            name: string;
            /** @enum {string} */
            type: "file" | "dir";
            /** Format: int64 */
            size: number;
            /** Format: date-time */
            update_time: string;
        };
        FileListResponse: {
            files: components["schemas"]["FileEntry"][];
        };
        UploadResponse: {
            /** @description Workspace-relative path of the stored file. */
            path: string;
            /** Format: int64 */
            size: number;
        };
        FileContentResponse: {
            path: string;
            content: string;
            size: number;
        };
        MCPTool: {
            /**
             * @example function
             * @enum {string}
             */
            type: "function";
            name: string;
            description: string;
            /** @description JSON Schema describing the tool's input parameters. */
            parameters: {
                [key: string]: unknown;
            };
        };
        MCPToolsResponse: {
            tools: components["schemas"]["MCPTool"][];
        };
        SkillEntry: {
            /** @description Skill identifier (the subdirectory name containing SKILL.md). */
            name: string;
            /** @description Same as `name`; the skill directory name. */
            filename: string;
            /** Format: int64 */
            size: number;
            /** Format: date-time */
            update_time: string;
        };
        SkillsResponse: {
            skills: components["schemas"]["SkillEntry"][];
        };
    };
    responses: {
        /** @description Malformed request body or missing field. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Operation not permitted (e.g. path outside workspace). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Uploaded file exceeds the size limit. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error. */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
